### ISSUE TITLE
Добавить ссылок на гайды и систематизировать

### ISSUE THREAD

**Issue by faergeek** [JS-Liberty/guide#2]
Пока просто ссылки покидаю. Тут всё что нужно хотя бы поглядеть. Не всё ещё смотрел сам. Про вью ничего добавить не могу, потому что юзаю реакт)

https://nano.sapegin.ru/all/stop-open-source-in-russian/
https://www.amazon.com/Head-First-HTML-CSS-Standards-Based/dp/0596159900
https://www.amazon.com/Mythical-Man-Month-Software-Engineering-Anniversary/dp/0201835959
https://www.amazon.com/Pragmatic-Programmer-journey-mastery-Anniversary/dp/0135957052
https://www.amazon.com/Pragmatic-Thinking-Learning-Refactor-Programmers/dp/1934356050
https://dou.ua/lenta/articles/what-you-should-know-about-algorithms/
https://mastery.games/p/flexbox-zombies
https://flexboxfroggy.com/
https://codepen.io/zefzero/pen/ALRgaK
http://devtoolschallenger.com/
https://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome
https://overreacted.io/
https://egghead.io/courses/getting-started-with-redux
https://egghead.io/courses/the-beginner-s-guide-to-react
https://www.youtube.com/channel/UCKjVLbSDoM-8-eEM7A30igA/playlists
https://mostly-adequate.gitbooks.io/mostly-adequate-guide/
https://github.com/getify/You-Dont-Know-JS
https://www.youtube.com/watch?v=ecIWPzGEbFc
https://reactjs.org/docs/getting-started.html
https://www.smashingmagazine.com/2019/11/express-es6-javascript-stack-mongodb-mongoose-servers/

**Comment by faergeek** [comment]
@faergeek https://github.com/getify/Functional-Light-JS

**Comment by faergeek** [comment]
@faergeek https://github.com/goldbergyoni/nodebestpractices

**Comment by faergeek** [comment]
@faergeek https://github.com/ryanmcdermott/clean-code-javascript
https://github.com/trekhleb/javascript-algorithms
https://github.com/vasanthk/web-security-basics
https://github.com/jamiebuilds/the-super-tiny-compiler
https://github.com/jamiebuilds/itsy-bitsy-data-structures

**Comment by faergeek** [comment]
@faergeek https://habr.com/ru/users/alexzfort/posts/

**Comment by faergeek** [comment]
@faergeek https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by SergUdo** [comment]
HTTP https://habr.com/ru/post/438810/

**Comment by SergUdo** [comment]
React in Rails https://sipsandbits.com/2019/03/01/how-to-react-on-rails/

**Comment by SergUdo** [comment]
Create React App + Rails 6.0 https://medium.com/@eth3rnit3/create-react-app-rails-6-0-custom-server-deployment-part-1-development-configuration-92ce11ea9c56

**Comment by SergUdo** [comment]
Песочница для регулярок https://regex101.com/

**Comment by SergUdo** [comment]
Английский по плейлистам https://www.youtube.com/channel/UC_3oKG5Szq-m6Xz-MjRZgpw

**Comment by SergUdo** [comment]
Подготовка к собеседованиям (Eng) https://github.com/MaximAbramchuck/awesome-interview-questions

**Comment by faergeek** [comment]
@SergUdo http://try.github.io/

**Comment by faergeek** [comment]
@faergeek https://nodeschool.io/

**Comment by faergeek** [comment]
https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/

**Comment by faergeek** [comment]
https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/
